### ISSUE TITLE
Remove extra dependencies

### ISSUE THREAD

**Issue by calebissharp** [M195/m#7]
There is some extra dependencies in `package.json` that don't need to be included.

**Comment by superoo7** [comment]
done removing these dependencies
``` json
{
  "body-parser": "^1.18.2",
  "cors": "^2.8.4",
  "express": "^4.16.1",
  "sentiment": "^4.0.1",
  "node-telegram-bot-api": "^0.28.0"
}
```

please accept [pull request](https://github.com/M195/m/pull/8)
