### ISSUE TITLE
Diversity of responses

### ISSUE THREAD

**Issue by wldwarrior** [M195/m#9]
The responses are very repetitive. Adding a larger diversity of responses would be awesome. Also possibly consider adding a simple math parser for inputs such as "2+2=?"?

**Comment by calebissharp** [comment]
Related to #6

**Comment by kostimarko** [comment]
Hi, I can also work on parts of this if need be.

**Comment by calebissharp** [comment]
I'll keep this issue open as to facilitate as many responses/patterns being implemented
